import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import {ReactNode} from "react";
import {cn} from "@/lib/utils";
import Navbar from "@/components/Navbar";
import CallToAction from "@/components/CallToAction";
import Footer from "@/components/Footer";
import Cursor from "@/components/Cursor";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aritra Bose',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={cn("min-h-screen antialiased cursor-none", inter.className)}>
        <Cursor/>
        <Navbar />
        {children}
        <CallToAction />
        <Footer />
      </body>
    </html>
  )
}
export default RootLayout;
